FROM node:latest

WORKDIR /app

COPY ./gym/package* .

RUN npm install

COPY ./gym ./

ARG USERNAME
ARG PASSWAOD 
ARG PORT
ARG HOST
ARG DATABASE
ARG SESSION
ARG IP
ARG BUCKETNAME
ARG AWSREGION

ENV NEXT_PUBLIC_DATABASE_USERNAME ${USERNAME}
ENV NEXT_PUBLIC_DATABASE_PASSWAOD ${PASSWAOD}
ENV NEXT_PUBLIC_DATABASE_PORT ${PORT}
ENV NEXT_PUBLIC_DATABASE_HOST ${HOST}
ENV NEXT_PUBLIC_DATABASE_DATABASE ${DATABASE}
ENV NEXT_PUBLIC_IRON_SESSION_PASSWORD ${PASSWORD}
ENV NEXT_PUBLIC_IP ${IP}
ENV AWS_BUCKET_NAME ${BUCKETNAME}
ENV AWS_REGION ${AWSREGION}

CMD ["pm2-runtime","start","npm","--","start"]
# CMD ["npm","run","start"]

