FROM node:latest

WORKDIR /app

COPY ./gym/package* .

RUN npm install && npm install --global pm2

ARG NEXT_PUBLIC_DATABASE_USERNAME
ARG NEXT_PUBLIC_DATABASE_PASSWAOD 
ARG NEXT_PUBLIC_DATABASE_PORT 
ARG NEXT_PUBLIC_DATABASE_HOST
ARG NEXT_PUBLIC_DATABASE_DATABASE
ARG NEXT_PUBLIC_IRON_SESSION_PASSWORD
ARG NEXT_PUBLIC_IP
ARG AWS_BUCKET_NAME
ARG AWS_REGION

COPY ./gym ./

CMD ["pm2-runtime","start","npm","--","start"]



